import date from './date.svg';
export * from './Eyes';
export * from './Check';
export { date };
import logo from './Logo.svg';
export { logo };
import bell from './bell.svg';
export { bell };
import broom from './broom.svg';
export { broom };
import calender from './calender.svg';
export { calender };
import watch from './watch.svg';
export { watch };
import background from './background.svg';
export { background };
export * from './LeftArrow';
export * from './RightArrow';
export * from './DotModal';
import DownArrow from './DownArrow.svg';
export { DownArrow };
import noSearch from './noSearch.svg';
export { noSearch };
export { default as profile } from './profile.svg';
export { default as mainpageImg } from './mainpage.svg';
export { default as backgroundLogo } from './backgroundLogo.svg';
export { default as laptop } from './laptop.svg';
export { default as nextSectionArrow } from './nextSectionArrow.svg';
export { default as phone } from './phone.svg';
export { default as threephone } from './threephone.svg';
export { default as twophone } from './twophone.svg';
export { default as nextphoneArrow } from './nextphoneArrow.svg';
export { default as download } from './download.svg';
